spring:
  threads:
    virtual:
      enabled: true
  application:
    name : toneup
  config:
    import: application-secret.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  datasource:
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 5
#      idle-timeout: 600000
#      max-lifetime: 1800000
  datasource:
    hikari:
      leak-detection-threshold: 5000

socketio:
  server:
    hostname: "localhost"
    port: 8081
#server:
#  tomcat:
#    threads:
#        max: 5
  servlet:
    encoding:
      force-response: true
logging:
  level:
    org:
      apache:
        coyote: DEBUG
    root: info

