spring:
  application:
    name : toneup
  config:
    import: classpath:application-secret.yml
socketio:
  server:
    hostname: "localhost"
    port: 8081
server:
  servlet:
    encoding:
      force-response: true
logging:
  level:
    root: info
